# Generated by Django 4.2.4 on 2023-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(default='2023-rGCa-24-moNW-8', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
