# Generated by Django 4.2.4 on 2023-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_order_ordernumber_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
