# Generated by Django 4.2.4 on 2023-08-24 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_order_notes_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('orderDate', models.DateField(default=datetime.datetime.today)),
                ('pdf', models.FileField(upload_to='invoices')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
