# Generated by Django 4.2.4 on 2023-08-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_product_madetoorder_alter_product_image_and_more'),
        ('customerApp', '0004_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customerApp.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='theCustomer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customerApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customerApp.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('linePriceTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theUser', to='customerApp.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theProd', to='storeApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='customerApp.lineitem'),
        ),
    ]
