# Generated by Django 4.2.4 on 2023-08-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0005_remove_invoice_lastname_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
