# Generated by Django 4.2.4 on 2023-08-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adultOnly',
            field=models.BooleanField(default=1),
        ),
    ]
