# Generated by Django 4.2.4 on 2023-08-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_category_adultonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='madeToOrder',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
