# Generated by Django 4.2.3 on 2023-08-31 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_remove_lineitem_customer_remove_lineitem_product_and_more'),
        ('storeApp', '0006_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='theCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custOrder', to='customerApp.user'),
        ),
    ]
