# Generated by Django 4.2.3 on 2023-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0007_alter_invoice_thecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[{'desc': 'Newly Placed', 'stat': 'New'}, {'desc': 'In discussion between Customer and Owner', 'stat': 'Pending'}, {'desc': 'Item is being created', 'stat': 'In Progress'}, {'desc': 'All items in order have been created', 'stat': 'Order Items Created'}, {'desc': 'Item has been shipped', 'stat': 'Shipped'}, {'desc': 'Item has been delivered', 'stat': 'Delivered'}, {'desc': 'Order was Rejected', 'stat': 'Rejected'}, {'desc': 'Order was Returned', 'stat': 'Returned'}, {'desc': 'Order was archived', 'stat': 'Archived'}], default='New', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[{'desc': 'New Order payment terms not set yet', 'stat': 'New'}, {'desc': 'Order is fully Paid for', 'stat': 'Paid'}, {'desc': 'Order is on a payment plan that in still ongoing', 'stat': 'Payment Plan'}, {'desc': 'Final Price determined and sent to customer', 'stat': 'Billed'}, {'desc': 'Order remains unpaid', 'stat': 'Unpaid'}, {'desc': 'Order is on hold awaiting terms', 'stat': 'On Hold'}], default='New', max_length=255),
        ),
    ]
